### ISSUE TITLE
No module named apiclient.discovery

### ISSUE THREAD

**Issue by alexhass** [robweber/xbmcbackup#120]
I always get this error in logs since I installed the backup software. It also complains on every system reboot about an error.

```
17:53:46.317 T:140682517800704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named apiclient.discovery
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.xbmcbackup/scheduler.py", line 9, in <module>
                                                from resources.lib.backup import XbmcBackup
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 7, in <module>
                                                from vfs import XBMCFileSystem,DropboxFileSystem,ZipFileSystem,GoogleDriveFilesystem
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 9, in <module>
                                                from pydrive.auth import GoogleAuth
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/pydrive/auth.py", line 6, in <module>
                                                from apiclient.discovery import build
                                            ImportError: No module named apiclient.discovery
                                            -->End of Python script error report<--

```

**Comment by rhermsen** [comment]
@robweber @alexhass 

Everyone has this issue (see post [1526](https://forum.kodi.tv/showthread.php?tid=129499&pid=2674731#pid2674731) and later on the kodi form).
Got the impression that two people solved the issue with using latest git release. (see post [1531](https://forum.kodi.tv/showthread.php?tid=129499&pid=2674800#pid2674800), [1535](https://forum.kodi.tv/showthread.php?tid=129499&pid=2674905#pid2674905), [1536](https://forum.kodi.tv/showthread.php?tid=129499&pid=2674908#pid2674908), but the posts have changed...)
Someone mentions that the following 3 add-ons have been receiving updates, just before the issue started (see post [1533](https://forum.kodi.tv/showthread.php?tid=129499&pid=2674862#pid2674862)):
```
Googleapi
IMDb scraper
Oauth2client 
```

**Comment by robweber** [comment]
Correct, the update to the GoogleAPI caused this. Fix will be pushed tomorrow. Sorry for the issues however it was kind of a chicken and the egg problem regarding dependencies. Just need to cleanup a few things in repo and issue a pull request.

**Comment by oomasoo** [comment]
Thanks ☺👍

**Comment by robweber** [comment]
Merge request for repo opened https://github.com/xbmc/repo-scripts/pull/692

**Comment by seanboy201** [comment]
How do I fix the error please I'm so stuck on programming my boxes without being able to install my back ups.. I've looked everywhere and I'm at a huge loss if I can't figure this out .. Please help me

**Comment by robweber** [comment]
Best case would be to just install the lastest zip file from the "master" branch of the repo. I've fixed the issues and issued the pull request for the Kodi repo, kind of just waiting on that approval now for it to replicate out.

**Comment by seanboy201** [comment]
Hi rob.. Is it possible u could provide me a download link. For. That
adon.. Please cause I'm not sure how to find a different version other then
the one that is already installed..  Any help would be great thanks...

**Comment by robweber** [comment]
https://github.com/robweber/xbmcbackup/archive/master.zip

**Comment by tchirou** [comment]
Hello
I have updated using the master zip
But I still have an error when I launch kodi
I don’t have an error when I manually launch the addon though
I haven’t tried to do a backup yet, I will check it makes a planned backup during the night as usual and report back
Thanks

**Comment by tknorris** [comment]
There's also a bug in this build in scheduler.py where if next_run.txt doesn't exist and the scheduler is turned on then nr doesn't get initialized so you get a UnboundLocalError.

                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'nr' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 189, in <module>
                                                BackupScheduler().start()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 38, in __init__
                                                if(0 < nr <= time.time() and utils.getSetting('schedule_miss') == 'true'):
                                            UnboundLocalError: local variable 'nr' referenced before assignment
                                            -->End of Python script error report<--

This fix, of course, is to set nr to 0 earlier in the method so this case is covered.

**Comment by seanboy201** [comment]
Hi rob I read all that but I don't understand.   When I try to make the
restore now it won't see the backup file that I have always used to restore
my stuff... In stuck any ideas brother?

**Comment by tchirou** [comment]
Ok the add on did nothing at 3am like if there was no planification

**Comment by robweber** [comment]
@tknorris  - created issue #124 . This feature was added in the newest release. 

For other issues please post a debug log if you're continuing to get errors. You should __not__ be getting the same apiclient.discovery error with this version (assuming deps are updated on your system). I'm getting lots of "yes this works" messages via the Kodi forum using the same zip file.

**Comment by tchirou** [comment]
Hello

Please find the log when I laucnh Kodi with the updated zip version

`15:46:30.470 T:138418295888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'nr' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 189, in <module>
                                                BackupScheduler().start()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 38, in __init__
                                                if(0 < nr <= time.time() and utils.getSetting('schedule_miss') == 'true'):
                                            UnboundLocalError: local variable 'nr' referenced before assignment
                                            -->End of Python script error `report<--``

Thanks

**Comment by seanboy201** [comment]
Its still not working. For me blahhh

**Comment by robweber** [comment]
Did you pull the latest git? I pushed some fixes for the scheduler just yesterday.

**Comment by seanboy201** [comment]
Yes i installed. The newest one u gave. Me but problem im having is that
when i got to restore it says the directory i chose is empty. Even though
its the same directory i always use to compleate the backup

**Comment by robweber** [comment]
The fix for this is merged so closing now. @seanboy201 - I created issue #125 to work on your problem as that is not related to this error.
